### PR TITLE
updated database with ossl functions/constants as of 0.9.2.1 

### PR DESCRIPTION
**Pull request by Makopo**
includes fix for #4

### CODE REVIEW

**Comment by Sei-Lisa** [comment]
Awesome update! Thank so much!

I see that outputs/last-func-const-check-os.txt has not been updated. This file is updated manually, by running the following programs and copy-pasting the outputs in the file in the appropriate places, overwriting the previous content:

- outputs/functioncheck-os.lsl (checks whether the functions exist, and the parameters and return values are valid, when possible)
- outputs/constant-test-os.lsl (checks that the values of the variables are correct - should catch any mismatch and it should have caught #4)

Unfortunately it's not possible to run them automatically, so they need to be run manually and the result pasted verbatim. Could you please do that and update the PR?

**Comment by Makopo** [comment]
I run the test script on 0.9.2.1 os server and receive this error:
```
Constants test run on 2023-03-05 in OpenSim OpenSim 0.9.2.1 Yeti Release (Unix/Mono)
Generated by LSL2 Derived Files Generator. Database version: 0.0.20230304000; output module version: 0.0.20140625000
Float constant value mismatch in line 835
Float constant value mismatch in line 836
Float constant value mismatch in line 837
Float constant value mismatch in line 838
Float constant value mismatch in line 839
Float constant value mismatch in line 840
Constants test finished with errors.
```

line 835-840:
```
,3.14159274f,PI
,6.28318548f,TWO_PI
,1.57079637f,PI_BY_TWO
,0.01745329238f,DEG_TO_RAD
,57.29578f,RAD_TO_DEG
,1.414213538f,SQRT2
```

I guess that small differences between double and float value causes this error but testing the script on master branch on 0.9.0.0-rc2 completes without error. 

The following code returns "differ".

```lsl
default
{
    state_entry()
    {
        if(PI_BY_TWO == 1.57079637f) {
            llOwnerSay("same");
        } else {
            llOwnerSay("differ");
        }
    }
}
```

**Comment by Sei-Lisa** [comment]
Thanks, indeed it looks like the float constants need to be updated too.

Anyway, I'm happy to merge it even with test failures for now, and deal with them separately. Could you please paste the results of both tests in outputs/last-func-const-check-os.txt and add the resulting file to the PR?

**Comment by Makopo** [comment]
Added resulting file to PR. Thank you.
FYI I suspect it's a YEngine issue, since it's not reproduced on XEngine even with version 0.9.2.1.

**Comment by Sei-Lisa** [comment]
Merged, thank you very much!

**Pull request merged**
